apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-order-deployment
  labels:
    app: ms-order
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ms-order
  template:
    metadata:
      labels:
        app: ms-order
    spec:
      containers:
        - name: ms-order
          image: svysk/ms-order:0.0.1
          ports:
            - name: http-order
              containerPort: 8080
          env:
          - name: DELIVERY_URL
            valueFrom:
              configMapKeyRef:
                name: order-configmap
                key: DELIVERY_URL

