apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-order-deployment
  namespace: marketplace
  labels:
    app: ms-order
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ms-order
  template:
    metadata:
      labels:
        app: ms-order
    spec:
      containers:
        - name: ms-order
          image: svysk/ms-order:0.1.0
          ports:
            - name: http-order
              containerPort: 8080
          resources:
            requests:
              memory: "128Mi"     # Minimum memory guaranteed
              cpu: "100m"         # Minimum CPU guaranteed (100m = 0.1 CPU)
            limits:
              memory: "256Mi"     # Maximum memory allowed
              cpu: "500m"         # Maximum CPU allowed (500m = 0.5 CPU)
          env:
          - name: DELIVERY_URL
            valueFrom:
              configMapKeyRef:
                name: order-configmap
                key: DELIVERY_URL
          - name: POSTGRES_URL
            valueFrom:
              configMapKeyRef:
                name: order-configmap
                key: POSTGRES_URL
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: order-postgres-secret
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: order-postgres-secret
                key: POSTGRES_PASSWORD


---
apiVersion: v1
kind: Service
metadata:
  name: ms-order
  namespace: marketplace
spec:
  selector:
    app: ms-order
  ports:
    - name: http-order
      port: 8080
      targetPort: http-order
      protocol: TCP