apiVersion: v1
kind: Service
metadata:
  name: ms-delivery
spec:
  selector:
    app: ms-delivery
  ports:
    - name: http-delivery
      port: 8081
      targetPort: http-delivery
      protocol: TCP