apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: marketplace  # Set the namespace for all resources

resources:
  # Core infrastructure
  - namespace.yaml
  - ingress.yaml

  # Kafka / zookeeper resources
  - kafka_zookeeper/zookeeper.yaml
  - kafka_zookeeper/kafka-statefulset.yaml
  - kafka_zookeeper/kafka-configmap.yaml

  # Microservice-specific resources (Order)
  - ms_order/order_app.yaml
  - ms_order/postgres.yaml
  - ms_order/postgres-secret.yaml
  - ms_order/configmap.yaml

  # Microservice-specific resources (Delivery)
  - ms_delivery/delivery_app.yaml
  - ms_delivery/postgres.yaml
  - ms_delivery/postgres-secret.yaml
  - ms_delivery/configmap.yaml
